markdown: kramdown
permalink: pretty 
highlighter: rouge
collections:
    thoughts:
        layout: page
        output: true
    projects:
        layout: page
        output: true
kramdown:
    input: GFM
    hard_wrap: false
gems:
  - jekyll-feed
