markdown: kramdown
permalink: pretty 
highlighter: rouge
collections:
    posts:
        layout: page
        output: true
kramdown:
    input: GFM
    hard_wrap: false
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
url: "https://sam.zhang.fyi"
